[project]
name = "langgraph_eng_package"
version = "0.0.1"
dependencies = [
    "bs4",
    "langgraph",
    "langchain_ollama",
    "langchain_core"
]

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"
